# Generated by Django 3.0.6 on 2020-05-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200524_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='writer',
        ),
    ]
