# Generated by Django 3.0.6 on 2020-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_article_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='descriptionEn',
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
